dist: bionic
language: go
os: linux
env:
  GO11MODULES=on
jobs:
  include:
    - go: "1.13.x"
    - go: "1.13.x"
      os: osx
    - go: "1.12.x"
install:
  - go get -t ./...
script: go test -v ./... -check.v
